name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      shell: bash
      run: npm i -g pnpm turbo

    # - uses: actions/cache@v3
    #   name: pnpm-cache
    #   id: pnpm-cache
    #   with:
    #     path: |
    #       **/node_modules
    #       ${{ steps.pnpm-cache-dir-path.outputs.dir }}
    #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm

    - name: pnpm
      shell: bash
      # if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline
