name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  claude-review:
    name: Claude Code Review
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Anthropic SDK
        run: npm install @anthropic-ai/sdk
        working-directory: /tmp

      - name: Claude Code Review
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          script: |
            const { Anthropic } = require('@anthropic-ai/sdk');
            
            if (!process.env.ANTHROPIC_API_KEY) {
              core.setFailed('ANTHROPIC_API_KEY secret is not set');
              return;
            }

            const anthropic = new Anthropic({
              apiKey: process.env.ANTHROPIC_API_KEY,
            });

            // Get PR details
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Get the diff for the PR
            const { data: diff } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              mediaType: {
                format: 'diff'
              }
            });

            // Prepare the prompt for Claude
            const prompt = `Please review this pull request and provide constructive feedback.

            PR Title: ${pr.title}
            PR Description: ${pr.body || 'No description provided'}

            Diff:
            \`\`\`diff
            ${diff}
            \`\`\`

            Please provide:
            1. Overall assessment of the changes
            2. Specific feedback on code quality, potential issues, and improvements
            3. Security considerations if applicable
            4. Performance implications if any
            5. Suggestions for better practices

            Format your response in markdown and be constructive and helpful.`;

            try {
              const response = await anthropic.messages.create({
                model: 'claude-3-5-sonnet-20241022',
                max_tokens: 4000,
                messages: [{
                  role: 'user',
                  content: prompt
                }]
              });

              const reviewComment = response.content[0].text;

              // Post the review as a comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## 🤖 Claude Code Review\n\n${reviewComment}\n\n---\n*This review was generated by Claude AI*`
              });

              console.log('Claude review posted successfully');
            } catch (error) {
              core.setFailed(`Failed to get Claude review: ${error.message}`);
            }